import type { Color, ColorableComponentName, FlyonUIVueAppDefaultConfig } from '@/Lib';

import type { ComputedRef, MaybeRefOrGetter, Ref } from 'vue';
import { useComponentClass }                       from '@/Lib/UseClass/Internal';
import { useFlyonUIVueAppConfigProperty }          from '@/Lib/UseFlyonUIVueAppConfig/Internal';

export function useColor(
    config: Ref<FlyonUIVueAppDefaultConfig>,
    componentName: MaybeRefOrGetter<ColorableComponentName>,
    color: MaybeRefOrGetter<Color | undefined>,
): ComputedRef<string> {
    const textClasses: Record<Color, string> = {
        neutral:   'text-neutral',
        primary:   'text-primary',
        secondary: 'text-secondary',
        accent:    'text-accent',
        info:      'text-info',
        success:   'text-success',
        warning:   'text-warning',
        error:     'text-error',
    };

    return useComponentClass<ColorableComponentName, Color>(
        componentName,
        {
            FoAlert: {
                neutral:   '',
                primary:   'alert-primary',
                secondary: 'alert-secondary',
                accent:    'alert-accent',
                info:      'alert-info',
                success:   'alert-success',
                warning:   'alert-warning',
                error:     'alert-error',
            },
            FoBadge: {
                neutral:   '',
                primary:   'badge-primary',
                secondary: 'badge-secondary',
                accent:    'badge-accent',
                info:      'badge-info',
                success:   'badge-success',
                warning:   'badge-warning',
                error:     'badge-error',
            },
            FoButton: {
                neutral:   '',
                primary:   'btn-primary',
                secondary: 'btn-secondary',
                accent:    'btn-accent',
                info:      'btn-info',
                success:   'btn-success',
                warning:   'btn-warning',
                error:     'btn-error',
            },
            FoCheckbox: {
                neutral:   '',
                primary:   'checkbox-primary',
                secondary: 'checkbox-secondary',
                accent:    'checkbox-accent',
                info:      'checkbox-info',
                success:   'checkbox-success',
                warning:   'checkbox-warning',
                error:     'checkbox-error',
            },
            FoDivider: {
                neutral:   'divider-neutral',
                primary:   'divider-primary',
                secondary: 'divider-secondary',
                accent:    'divider-accent',
                info:      'divider-info',
                success:   'divider-success',
                warning:   'divider-warning',
                error:     'divider-error',
            },
            FoHeading: textClasses,
            FoLink:    {
                neutral:   'link-neutral',
                primary:   'link-primary',
                secondary: 'link-secondary',
                accent:    'link-accent',
                info:      'link-info',
                success:   'link-success',
                warning:   'link-warning',
                error:     'link-error',
            },
            FoModal: {
                neutral:   'bg-base-300/60',
                primary:   'bg-primary/30',
                secondary: 'bg-secondary/30',
                accent:    'bg-accent/30',
                info:      'bg-info/30',
                success:   'bg-success/30',
                warning:   'bg-warning/30',
                error:     'bg-error/30',
            },
            FoLoading:        textClasses,
            FoRadialProgress: textClasses,
            FoRadio:          {
                neutral:   '',
                primary:   'radio-primary',
                secondary: 'radio-secondary',
                accent:    'radio-accent',
                info:      'radio-info',
                success:   'radio-success',
                warning:   'radio-warning',
                error:     'radio-error',
            },
            FoRange: {
                neutral:   '',
                primary:   'range-primary',
                secondary: 'range-secondary',
                accent:    'range-accent',
                info:      'range-info',
                success:   'range-success',
                warning:   'range-warning',
                error:     'range-error',
            },
            FoStatus: {
                neutral:   '',
                primary:   'status-primary',
                secondary: 'status-secondary',
                accent:    'status-accent',
                info:      'status-info',
                success:   'status-success',
                warning:   'status-warning',
                error:     'status-error',
            },
            FoSwitch: {
                neutral:   '',
                primary:   'switch-primary',
                secondary: 'switch-secondary',
                accent:    'switch-accent',
                info:      'switch-info',
                success:   'switch-success',
                warning:   'switch-warning',
                error:     'switch-error',
            },
            FoTooltip: {
                neutral:   '',
                primary:   'tooltip-primary',
                secondary: 'tooltip-secondary',
                accent:    'tooltip-accent',
                info:      'tooltip-info',
                success:   'tooltip-success',
                warning:   'tooltip-warning',
                error:     'tooltip-error',
            },
        },
        useFlyonUIVueAppConfigProperty(config, componentName, 'color', color),
    );
}
