/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FoBadge: typeof import('./src/UI/Components/Badge/UI/FoBadge.vue')['default']
    FoButton: typeof import('./src/UI/Components/Button/UI/FoButton.vue')['default']
    FoCheckbox: typeof import('./src/UI/Forms/Checkbox/UI/FoCheckbox.vue')['default']
    FoCheckboxGroup: typeof import('./src/UI/Forms/Checkbox/UI/FoCheckboxGroup.vue')['default']
    FoDatalist: typeof import('./src/UI/Forms/Select/UI/FoDatalist.vue')['default']
    FoDatatable: typeof import('./src/UI/Tables/Datatable/UI/FoDatatable.vue')['default']
    FoDotStyleBadge: typeof import('./src/UI/Components/Badge/UI/FoDotStyleBadge.vue')['default']
    FoFragment: typeof import('./src/UI/Components/Fragment/Internal/UI/FoFragment.vue')['default']
    FoHeading: typeof import('./src/UI/Content/Heading/UI/FoHeading.vue')['default']
    FoHelperText: typeof import('./src/UI/Components/HelperText/Internal/UI/FoHelperText.vue')['default']
    FoIcon: typeof import('./src/UI/Customization/Icon/UI/FoIcon.vue')['default']
    FoInlineLabel: typeof import('./src/UI/Components/Label/UI/FoInlineLabel.vue')['default']
    FoInputText: typeof import('./src/UI/Forms/InputText/UI/FoInputText.vue')['default']
    FoJoin: typeof import('./src/UI/Forms/Join/UI/FoJoin.vue')['default']
    FoKeyboard: typeof import('./src/UI/Content/Keyboard/UI/FoKeyboard.vue')['default']
    FoLabel: typeof import('./src/UI/Components/Label/Internal/UI/FoLabel.vue')['default']
    FoLink: typeof import('./src/UI/Content/Link/UI/FoLink.vue')['default']
    FoListGroup: typeof import('./src/UI/Components/ListGroup/UI/FoListGroup.vue')['default']
    FoListGroupItem: typeof import('./src/UI/Components/ListGroup/UI/FoListGroupItem.vue')['default']
    FoLoading: typeof import('./src/UI/Components/Loading/UI/FoLoading.vue')['default']
    FoLoadingButton: typeof import('./src/UI/Components/Button/UI/FoLoadingButton.vue')['default']
    FoMenu: typeof import('./src/UI/Components/Menu/UI/FoMenu.vue')['default']
    FoMenuItem: typeof import('./src/UI/Components/Menu/UI/FoMenuItem.vue')['default']
    FoMenuParentTitle: typeof import('./src/UI/Components/Menu/UI/FoMenuParentTitle.vue')['default']
    FoMenuTitle: typeof import('./src/UI/Components/Menu/UI/FoMenuTitle.vue')['default']
    FoModal: typeof import('./src/UI/Overlays/Modal/UI/FoModal.vue')['default']
    FoModalTitle: typeof import('./src/UI/Overlays/Modal/UI/FoModalTitle.vue')['default']
    FoNavbar: typeof import('./src/UI/Components/Navbar/UI/FoNavbar.vue')['default']
    FoNavbarBrand: typeof import('./src/UI/Components/Navbar/UI/FoNavbarBrand.vue')['default']
    FoNavbarHamburgerMenuToggler: typeof import('./src/UI/Components/Navbar/UI/FoNavbarHamburgerMenuToggler.vue')['default']
    FoNavbarLinkList: typeof import('./src/UI/Components/Navbar/UI/FoNavbarLinkList.vue')['default']
    FoPagination: typeof import('./src/UI/Navigations/Pagination/UI/FoPagination.vue')['default']
    FoPaginationButton: typeof import('./src/UI/Navigations/Pagination/Internal/UI/FoPaginationButton.vue')['default']
    FoPopover: typeof import('./src/UI/Overlays/Popover/UI/FoPopover.vue')['default']
    FoRouterLink: typeof import('./src/UI/Content/Link/Internal/UI/FoRouterLink.vue')['default']
    FoSelect: typeof import('./src/UI/Forms/Select/UI/FoSelect.vue')['default']
    FoSelectOption: typeof import('./src/UI/Forms/Select/Internal/UI/FoSelectOption.vue')['default']
    FoSelectThemeController: typeof import('./src/UI/Components/ThemeController/UI/FoSelectThemeController.vue')['default']
    FoSocialButton: typeof import('./src/UI/Components/Button/UI/FoSocialButton.vue')['default']
    FoStat: typeof import('./src/UI/Components/Stats/UI/FoStat.vue')['default']
    FoStatActions: typeof import('./src/UI/Components/Stats/UI/FoStatActions.vue')['default']
    FoStatDescription: typeof import('./src/UI/Components/Stats/UI/FoStatDescription.vue')['default']
    FoStatFigure: typeof import('./src/UI/Components/Stats/UI/FoStatFigure.vue')['default']
    FoStats: typeof import('./src/UI/Components/Stats/UI/FoStats.vue')['default']
    FoStatTitle: typeof import('./src/UI/Components/Stats/UI/FoStatTitle.vue')['default']
    FoStatValue: typeof import('./src/UI/Components/Stats/UI/FoStatValue.vue')['default']
    FoSwap: typeof import('./src/UI/Components/Swap/UI/FoSwap.vue')['default']
    FoTable: typeof import('./src/UI/Tables/Table/UI/FoTable.vue')['default']
    FoTableBody: typeof import('./src/UI/Tables/Table/UI/FoTableBody.vue')['default']
    FoTableColumn: typeof import('./src/UI/Tables/Table/UI/FoTableColumn.vue')['default']
    FoTableHead: typeof import('./src/UI/Tables/Table/UI/FoTableHead.vue')['default']
    FoTableHeader: typeof import('./src/UI/Tables/Table/UI/FoTableHeader.vue')['default']
    FoTableRow: typeof import('./src/UI/Tables/Table/UI/FoTableRow.vue')['default']
    FoTextarea: typeof import('./src/UI/Forms/Textarea/UI/FoTextarea.vue')['default']
    FoTooltip: typeof import('./src/UI/Overlays/Tooltip/UI/FoTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
