import type { ConfigurableComponentProps } from '@/Lib';

type NonConfigurableComponentName = 'FoAvatarGroup'
    | 'FoBlockQuote'
    | 'FoCheckboxGroup'
    | 'FoDataList'
    | 'FoDataTable'
    | 'FoDiff'
    | 'FoDotStyleBadge'
    | 'FoJoin'
    | 'FoImageRadio'
    | 'FoLabel'
    | 'FoListGroup'
    | 'FoListGroupItem'
    | 'FoLoadingButton'
    | 'FoMenuItem'
    | 'FoModalTitle'
    | 'FoMultipleSelect'
    | 'FoPagination'
    | 'FoPopover'
    | 'FoSkeleton'
    | 'FoSocialButton'
    | 'FoStat'
    | 'FoStatDescription'
    | 'FoStats'
    | 'FoStatTitle'
    | 'FoStatValue'
    | 'FoSwap'
    | 'FoSwitchGroup'
    | 'FoTab'
    | 'FoTableBody'
    | 'FoTableColumn'
    | 'FoTabContent'
    | 'FoTableHead'
    | 'FoTableHeader'
    | 'FoTableRow';

export type ConfigurableComponentName = keyof ConfigurableComponentProps;
export type ComponentName = ConfigurableComponentName | NonConfigurableComponentName;
